FIRST, SECOND, THIRD, FORTH, FIFTH, SIXTH, ORDERID, CAT_NAME, GOODBYE, ADMIN_CATEGORIES, ADD_CATEGORY, WAITING_FOR_CATEGORY, CATEGORY_ADDED, MANAGE_CATEGORIES, DELETE_CATEGORY, CANCEL_ADD = range(16)
